Add codebooks for sdg 2, 3 and 4
nestauk/sdg-mapping pull request #19
Opened 2020-06-16 14:02 UTC by dede95

2020-06-23 17:55 UTC, georgerichardson requested changes

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +There are two Sustainable Development Goals that have aspects that are closely related to Goal 1. These are:
```suggestion
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +  - Concerns about climate change on the ecosystem
```suggestion
  - Covers broader impacts of climate change on all land based ecosystems
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +Remember, many projects will cover more than one Goal, but to be tagged as Goal 1 they must include at least one of the Key Concepts above. Further information on other goals can be found [here](http
```suggestion
Remember, many projects will cover more than one Goal, but to be tagged as Goal 2 they must include at least one of the Key Concepts above. Further information on other goals can be found [here](https://unstats.un.org/sdgs/metadata/).
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +| Project discussing capacity of freshwater bodies                                      | No         |
```suggestion
| Study measuring the physical capacity of freshwater bodies                                      | No         |
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +hunger, world hunger, food, agriculture, malnutrition, farmers, fishers, food production, food producers, food access, nutrition, sufficient food, malnutrition, food systems, famines, starvation, veg
```suggestion
hunger, world hunger, food, agriculture, malnutrition, farmers, fishers, food production, food producers, food access, nutrition, sufficient food, malnutrition, food systems, famines, starvation, vegetation, minerals, healthy food, vitamins, crop, crop yield, crop production, food commodities, drought, smallholder, genetic resources, soil quality, agricultural practice, seed bank, agricultural markets 
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +To be labelled with `Yes`, a project should explicitly or implicitly refer to at least one of these. More detail on the specific targets is provided below.
```suggestion
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +To be labelled with `Yes`, a project should explicitly or implicitly refer to at least one of these. More detail on the specific targets is provided below.
```suggestion
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +* There are specific goals for consequences of consumption and production, gender and reducing inequality. Please only label projects `Yes` if they mainly relate to these areas in the context of stat
```suggestion
* There are specific goals for broader gender inequality and other inequalities. Please only label projects `Yes` if they concern equality in a health-specific context.

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +  - Concerns the impact of chemicals and waste on not only human health but also environmental health
```suggestion
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +| Project discussing imagining strategies on patients with intermediate risk of coronary artery disease                                    | Yes        |
imaging? (instead of imagining)

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +| Project discussing metabolic interactions in oceanic photosymbioses                                    | No         |
```suggestion
| Project discussing metabolic interactions in oceanic ecosystems                                    | No         |

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +- Increase agricultural productivity and incomes of small-scale food producers
```suggestion
- Agricultural productivity and incomes of small-scale food producers
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +- Agricultural research related to food/human consumption (not biofuels, etc)
```suggestion
- Agricultural research related to food for human consumption (not biofuels, etc)
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +- Improving the health of millions
```suggestion
- Improving human health

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +- Increase life expectancy and reduce deaths caused by external factors such as road traffic accidents
```suggestion
- Increase life expectancy 
- Infant mortality
- Reduce deaths caused by external factors e.g.. road traffic accidents

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +- Reduce the global maternal mortality ratio
```suggestion
- Reduce the global maternal mortality rate

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +- Reduce the global maternal mortality ratio
I know this goal says 'ratio' but I think out of context 'rate' makes more sense

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +- End the epidemics of diseases and premature deaths caused by such diseases
```suggestion
- Epidemics and related premature deaths
- Communicable and non-communicable diseases
- Mental health, well-being and suicide
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +To be labelled with `Yes`, a project should explicitly or implicitly refer to at least one of:
```suggestion
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +- Ensure all children have access to quality and free pre-primary childhood development, care and education.
```suggestion
- Quality and free, equitable and quality primary and secondary education
- Quality and free pre-primary childhood development, care and education
- Access to tertiary education and university

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +- Equal access for men and women affordable vocational, technical and tertiary education
```suggestion
- Equal access for men and women to vocational, technical and tertiary education

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +- Achieve literacy and numeracy amongst youth and some adults
```suggestion
- Literacy and numeracy for youth and adults

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +- Increase in number of youth and adults who have relevant skills for employment and entrepreneurship
```suggestion
- Relevant skills for employment and entrepreneurship for youth and adults

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +- Leaners to acquire knowledge and skills needed to promote sustainable development such as human rights, gender equality, promotion of cultural diversity, etc*
```suggestion
- Learning knowledge and skills to promote sustainable development such as human rights, gender equality, promotion of cultural diversity, etc* 

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +- increase the supply of qualified teachers and scholarships available to developing countries
```suggestion
- Supply of qualified teachers and scholarships available to developing countries
- Education facilities that are safe and child, disability and gender sensitive
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +- Access to health-care services*
```suggestion
- Access to health-care services*
- Universal health coverage, health insurance and access to medicines
- Development, training and retention of the health workforce
- Early warning, risk reduction and management of national/international health risks
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_3.md
> +- Prevention and treatment of substance abuse
```suggestion
- Prevention and treatment of substance abuse (incl. tobacco)

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_2.md
> +- Sustainable and resilient food production systems
```suggestion
- Sustainable and resilient food production systems
- Climate adaptation in agriculture
- Soil quality
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +  - Focus on types of work conditions and improving working environments
```suggestion
```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +  - Concerns gender equality in various areas, not just education (specifically on reproductive health)
```suggestion
  - Concerns broader gender equality

```

2020-06-23 17:55 UTC, georgerichardson commented on codebooks/codebook_sdg_4.md
> +| Project discussing improving the knowledge of organised crime                    | No         |
```suggestion
| Development of non-education related games for children                    | No         |

```

2020-06-24 15:41 UTC, dede95 commented on codebooks/codebook_sdg_3.md
> +| Project discussing imagining strategies on patients with intermediate risk of coronary artery disease                                    | Yes        |
```suggestion
| Project discussing imaging strategies on patients with intermediate risk of coronary artery disease                                    | Yes        |

```

2020-06-24 16:02 UTC, merged